# Use the official Nginx image from Docker Hub
FROM nginx:alpine

# Copy the custom nginx.conf to the container
COPY conf/nginx.conf /etc/nginx/nginx.conf

# Expose port 5423 to access Nginx
EXPOSE 5423
